language: go
stages:
  - lint
  - test
go:
  - 1.11.x
  - 1.12.x

stage: test
install: skip
script:
  - make test
jobs:
  include:
    - stage: lint
      go: 1.12.x
      install:
        - GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.17.1
      script:
        - make lint
    - stage: test
      os: windows
      go: 1.12.x
      language: go
      script:
        - go test
    - stage: test
      os: osx
      osx_image: xcode10.1
      go: 1.12.x
      language: go
